# Generated by Django 5.2.6 on 2025-10-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='caseaption',
            new_name='caption',
        ),
    ]
